MISSING_PARAMS = u"I think you forgot some parameters :thinking_face:"
OK = u"OK :+1:"
PLEASE_SUBSCRIBE = u"if you want to participate in this survey, use the `join` command to subscribe"
INVALID_TIME = u"invalid time: `{}`"
GREET_USER = u"{} {} :wave: Let's talk in private :wink:"
#answers
ANSWERS_TOO_FEW = u"Hey...I think you forgot to enter some answers. I was expecting *{}* answers but only got *{}*."
ANSWERS_TOO_MANY = u"Whoa! You entered too many answers. I was expecting *{}* answers but you entered *{}*."
ANSWERS_INVALID = u"invalid answer :thinking_face:"
ANSWERS_BAD_CHOICE = u"invalid choice for question *{}* :confused:"
ANSWERS_SAVE_OK = u"answer saved :+1:"
ANSWERS_SAVE_FAIL = u"error saving answer :cold_sweat:"
ANSWERS_CONFIRM = u"If you are happy with your reponses hit `ok`, otherwise enter a new response. \nType `notes` to add a short note to this answer. \nYou can also `cancel` this answer. "
ANSWERS_DELETE_OK = u"All your answers to the _{}_ survey are gone :skull:"	
ANSWERS_DELETE_FAIL = u"I could not delete your _{}_ survey answers :cold_sweat:"
ANSWERS_ADD_NOTE = u":writing_hand: enter a short note about your survey"

#surveys
SURVEY_NOT_SUBSCRIBED = u"you are not subscribed to survey _{}_ :unamused:"
SURVEY_IS_SUBSCRIBED = u":hugging_face: you aready subscribed survey _{}_ "
SURVEY_UNKNOWN = u"_{}_ survey does not exist :unamused:"
SURVEY_JOIN_OK = u"_{}_ survey subscribed :hugging_face:"	
SURVEY_JOIN_FAIL = u"could not subscribe survey _{}_ :cold_sweat:"
SURVEY_LEAVE_OK = u"you left the _{}_ survey. \nI will keep your data and you can subscribe this survey again anytime you want. :relaxed: \nUse the `delete` command if you want wipe all of your answers"	
SURVEY_LEAVE_FAIL = u"could not leave survey _{}_ :cold_sweat:"
SURVEY_CANCELED = u"survey canceled :neutral_face:"

#reminders
REMINDER_OK = u"I will remind you to take the _{}_ survey  at `{}`"	
REMINDER_OK_2 = u"I will remind you to take the  _{}_  survey at `{}` and again at `{}`" 	
REMINDER_FAIL = u"could not set reminder for _{}_ survey  :cold_sweat:"
REMINDER_REMOVE_OK = u"No more reminders for the _{}_ survey :v:"
REMIND_SURVEY = u"Psst! Don't forget to take the _{}_ survey ({}) :wink:" 
#report
REPORT_FAIL = u"could not retrieve answers for survey _{}_ :cold_sweat:"
REPORT_EMPTY = u"you have no answers for the _{}_ survey "
NOTES_EMPTY = u"you don't have notes for the _{}_ survey "
